package server

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// hookMarker identifies hooks we generated, so install-hook never clobbers a
// hand-written one.
const hookMarker = "# generated by local-preview (preview install-hook)"

const hookScript = `#!/bin/sh
` + hookMarker + `
preview deploy "$(git rev-parse HEAD)" --no-wait >/dev/null 2>&1 || true
`

// preCommitStanza is printed (never auto-applied — silently mutating a file
// the pre-commit framework re-parses is riskier than asking the user to
// paste) when the target repo already uses the pre-commit framework.
const preCommitStanza = `  - repo: local
    hooks:
      - id: local-preview
        name: local-preview deploy
        entry: sh -c 'preview deploy "$(git rev-parse HEAD)" --no-wait'
        language: system
        stages: [post-commit]
        always_run: true
        pass_filenames: false
`

func installHookCmd() *cobra.Command {
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "install-hook",
		Short: "Install a post-commit hook that deploys every commit",
		Long: "Run from inside a target repository's working tree. Installs a git\n" +
			"post-commit hook that requests a preview deploy of each new commit.\n" +
			"If the repo uses the pre-commit framework, the equivalent stanza is\n" +
			"printed for .pre-commit-config.yaml instead.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInstallHook(cmd.Context(), cmd.OutOrStdout(), dryRun)
		},
	}
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Print what would be written without writing it")
	return cmd
}

func runInstallHook(ctx context.Context, out io.Writer, dryRun bool) error {
	top, err := findWorktreeRoot(".")
	if err != nil {
		return fmt.Errorf("not inside a git working tree: %w", err)
	}

	if _, err := os.Stat(filepath.Join(top, ".pre-commit-config.yaml")); err == nil {
		fmt.Fprintf(out, "This repo uses the pre-commit framework. Add this hook to .pre-commit-config.yaml\n")
		fmt.Fprintf(out, "(and install the post-commit stage with `pre-commit install --hook-type post-commit`):\n\n")
		fmt.Fprint(out, preCommitStanza)
		return nil
	}

	gitDir, err := localGitDir(top)
	if err != nil {
		return err
	}
	hookPath := filepath.Join(gitDir, "hooks", "post-commit")

	if existing, err := os.ReadFile(hookPath); err == nil && !strings.Contains(string(existing), hookMarker) {
		return fmt.Errorf("%s already exists and wasn't generated by local-preview — add this line to it yourself:\n  preview deploy \"$(git rev-parse HEAD)\" --no-wait || true", hookPath)
	}

	if dryRun {
		fmt.Fprintf(out, "would write %s:\n\n%s", hookPath, hookScript)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(hookPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(hookPath, []byte(hookScript), 0o755); err != nil {
		return err
	}
	fmt.Fprintf(out, "installed %s — every commit now deploys a preview\n", hookPath)
	return nil
}
